### ISSUE TITLE
Unable to buld firmware

### ISSUE THREAD

**Issue by nonolk** [mongoose-os-apps/mel-ac-homekit#3]
Hello I'm trying to build this app using either VScode or directly mos build, it ends with an error on compilation:
too many arguments to function 'cs_base64_encode'

Which version of Mongoose should I use, I'm trying to compile using 2.19.1 is this supported ?

Best regards

**Comment by d4rkmen** [comment]
`20210617-194609/2.19.1-30-gf08e2c6-master`
```
$ mos build --platform ESP32
Connecting to https://build.mongoose-os.com, user test
Uploading sources (25932 bytes)
Firmware saved to C:\Work\GitHub\mel-ac-homekit\build\fw.zip
By the way, there is a newer version available: "202111281334" (you use "202106171938"). Run "mos update" to upgrade.
Command completed.
```
Update your mos tool please, closing this
